import { describe, it, expect, beforeEach } from 'vitest';
import { component, html } from '../src/lib/index';
import { parseSpaceUtility, jitCSS } from '../src/lib/runtime/style';

describe('Space utilities (space-x-* and space-y-*)', () => {
  beforeEach(() => {
    document.body.innerHTML = '';
  });

  it('should parse space-x-* classes', () => {
    const result = parseSpaceUtility('space-x-4');
    
    expect(result).toBeTruthy();
    expect(result).toContain('--ce-space-x-reverse:0');
    expect(result).toContain('margin-inline-start');
    expect(result).toContain('margin-inline-end');
    expect(result).toContain('> :not([hidden]) ~ :not([hidden])');
    expect(result).toContain('calc(0.25rem * 4)');
  });

  it('should parse space-y-* classes', () => {
    const result = parseSpaceUtility('space-y-2');
    
    expect(result).toBeTruthy();
    expect(result).toContain('--ce-space-y-reverse:0');
    expect(result).toContain('margin-top');
    expect(result).toContain('margin-bottom');
    expect(result).toContain('> :not([hidden]) ~ :not([hidden])');
    expect(result).toContain('calc(0.25rem * 2)');
  });

  it('should handle negative space values', () => {
    const resultX = parseSpaceUtility('-space-x-4');
    const resultY = parseSpaceUtility('-space-y-2');
    
    expect(resultX).toContain('calc(-0.25rem * 4)');
    expect(resultY).toContain('calc(-0.25rem * 2)');
  });

  it('should handle fractional space values', () => {
    const resultX = parseSpaceUtility('space-x-1/2');
    const resultY = parseSpaceUtility('space-y-1/4');
    
    expect(resultX).toContain('50%');
    expect(resultY).toContain('25%');
  });

  it('should handle space-x-reverse and space-y-reverse', () => {
    const resultX = parseSpaceUtility('space-x-reverse');
    const resultY = parseSpaceUtility('space-y-reverse');
    
    expect(resultX).toBe('--ce-space-x-reverse:1;');
    expect(resultY).toBe('--ce-space-y-reverse:1;');
  });

  it('should return null for invalid inputs', () => {
    expect(parseSpaceUtility('space-z-4')).toBeNull();
    expect(parseSpaceUtility('spacing-x-4')).toBeNull();
    expect(parseSpaceUtility('space-x-abc')).toBeNull();
    expect(parseSpaceUtility('space-x')).toBeNull();
  });

  it('should generate CSS with jitCSS for space-x classes', () => {
    const html = '<div class="space-x-4 space-x-2 space-x-8"></div>';
    const css = jitCSS(html);
    
    expect(css).toContain('space-x-4');
    expect(css).toContain('space-x-2');
    expect(css).toContain('space-x-8');
    expect(css).toContain('--ce-space-x-reverse:0');
  });

  it('should generate CSS with jitCSS for space-y classes', () => {
    const html = '<div class="space-y-4 space-y-2"></div>';
    const css = jitCSS(html);
    
    expect(css).toContain('space-y-4');
    expect(css).toContain('space-y-2');
    expect(css).toContain('--ce-space-y-reverse:0');
  });

  it('should apply space-x in a real component', async () => {
    component('test-space-x', () => {
      return html`
        <div class="space-x-4 flex">
          <div class="bg-primary-500 p-2">Item 1</div>
          <div class="bg-secondary-500 p-2">Item 2</div>
          <div class="bg-success-500 p-2">Item 3</div>
        </div>
      `;
    });

    const el = document.createElement('test-space-x') as any;
    document.body.appendChild(el);
    await new Promise(resolve => setTimeout(resolve, 50));

    const wrapper = el.shadowRoot.querySelector('div');
    expect(wrapper).toBeTruthy();
    expect(wrapper.className).toContain('space-x-4');
    
    // Verify CSS was generated by checking adoptedStyleSheets exist
    expect(el.shadowRoot.adoptedStyleSheets.length).toBeGreaterThan(0);
  });

  it('should apply space-y in a real component', async () => {
    component('test-space-y', () => {
      return html`
        <div class="space-y-2">
          <div class="bg-primary-500 p-2">Item 1</div>
          <div class="bg-secondary-500 p-2">Item 2</div>
          <div class="bg-success-500 p-2">Item 3</div>
        </div>
      `;
    });

    const el = document.createElement('test-space-y') as any;
    document.body.appendChild(el);
    await new Promise(resolve => setTimeout(resolve, 50));

    const wrapper = el.shadowRoot.querySelector('div');
    expect(wrapper).toBeTruthy();
    expect(wrapper.className).toContain('space-y-2');
    
    // Verify CSS was generated by checking adoptedStyleSheets exist
    expect(el.shadowRoot.adoptedStyleSheets.length).toBeGreaterThan(0);
  });

  it('should work with variants like hover: and md:', () => {
    const html = '<div class="md:space-x-8 hover:space-y-4"></div>';
    const css = jitCSS(html);
    
    expect(css).toContain('@media');
    expect(css).toContain('space-x-8');
    expect(css).toContain(':hover');
    expect(css).toContain('space-y-4');
  });
});
